app: yangskitchen-menu-api
service: yangskitchen-menu-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: us-east-1
  environment:
    SERVERLESS: true
    GOOGLE_SHEET_ID: ${file(./env.${opt:stage, self:provider.stage, 'dev'}.json):GOOGLE_SHEET_ID}
    GOOGLE_SHEETS_API_KEY: ${file(./env.${opt:stage, self:provider.stage, 'dev'}.json):GOOGLE_SHEETS_API_KEY}
    MEMCACHED_URL: ${file(./env.${opt:stage, self:provider.stage, 'dev'}.json):MEMCACHED_URL}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  serverless-offline:
    httpPort: 8080
